### ISSUE TITLE
Make opt drive move conditional on the existence of a second disk device

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/hydra-ubuntu#1]
In simple configurations, especially portable VMs, it would be nice if the scripts would work without having to have a second disk device for opt.  Maybe do this by detecting it's existence in these roles:
./roles/vagrant-housekeeping/tasks/vagrant_housekeeping.yml
./roles/housekeeping/tasks/ec2_housekeeping.yml

**Comment by acozine** [comment]
We could simply change the vagrant-housekeeping role's default install_path to /home/vagrant/install and leave the /opt drive alone in all vagrant builds. I originally built the vagrant stuff this way so we could build a vagrant VM that was a clone of production. But that seems like an unpopular use case. Do we still need to build production-style vagrant VMs?

**Comment by mark-dce** [comment]
How does the underlying mount point relate to where we point the install path? On both Vagrant and AWS all of our virtual system and opt drives probably end up on the same physical hardware ( or spread across the same massive raid arrays in the AWS case) but it's not like the separate opt drive is really a real-world thing - Isn't it just an abstraction that makes it easier to compartmentalize things when we want to add more data space?  Or is there more to it that I'm not getting?

**Comment by mark-dce** [comment]
Separated out into a configurable role - see 5957bb726bd596d01b52dba099e1335384cfe513
