### ISSUE TITLE
Skip downloading if re-running provisioning scripts and the needed file is already available 

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/hydra-ubuntu#2]
For any of the tasks that download a file from a remote source, consider adding a `when` condition that checks for the existence of the download file.

**Comment by acozine** [comment]
The "dest" parameter on the get_url module does this. See http://docs.ansible.com/ansible/get_url_module.html. I know this parameter is set on most if not all of the get_url tasks.

**Comment by mark-dce** [comment]
You're right and it looks like it's there for all get_url task.  I was seeing this behavior in part because I was destroying my VM between some runs to ensure I wasn't inadvertently saving state from a previous run (like downloaded install files - pibcak ;) )
